### ISSUE TITLE
what about r-lib verse

### ISSUE THREAD

**Issue by cboettig** [ropensci/dotgithubfiles#4]
As @jennybc mentioned in https://github.com/ropensci/onboarding-meta/issues/13, sounds like devtools etc will soon be providing`use_` functions to create some of this?  Obviously we can create our own as necessary, but for some of these maybe better to coordinate first with those efforts?  I dunno, but I'm all for shared / common practices and fewer things we have to maintain independently... Perhaps @jennybc can weigh in more insightfully.

**Comment by jennybc** [comment]
I think there are 2-3 points.

  1. devtools is getting broken up into pieces and all the `use_*()` functions will live in usethis. The existing ones and future ones.
  1. I think/hope usethis will then be free to be less focused on R *packages*. For example, you could use it to create a `README.Rmd` file w/o getting an error just because your project doesn't seem to be an R package.
  1. It would be interesting for entities (whatever that means) like the tidyverse or rOpenSci to be able to publish templates accessible via usethis functions. You can imagine various ways of implementing that.

**Comment by maelle** [comment]
> It would be interesting for entities (whatever that means) like the tidyverse or rOpenSci to be able to publish templates accessible via usethis functions. You can imagine various ways of implementing that.

What's the current state-of-the-art @jennybc?

**Comment by jennybc** [comment]
`usethis::use_template()` is now exported and has a `package =` argument for using templates from other packages.

**Comment by maelle** [comment]
Thanks, fantastic! I should have read the doc 🙈

**Comment by maelle** [comment]
[`rodev`](https://github.com/ropenscilabs/rodev) now has a `use_ro_github` function based on `usethis::use_template`. Thanks for exporting it @jennybc!

Our CONTRIBUTING.md is adapted from tidyverse one, which is acknowledged at the bottom of the template.
